<!DOCTYPE html>

<html>
	<head>
		<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" >
		<link rel="stylesheet" type="text/css" href="<?= $this->_getStyleURL () ?>" />
		<link rel="icon" type="image/x-icon" href="<?= $this->getSkinUrl ("favicon.ico") ?>"  />
	</head>
	<body>
		<div id="message" ><?= strip_tags ( $this->getMessagesBlock ()->getGroupedHtml () ) ?></div>
		<table id="jetrails-twofactor-verify" cellpadding="0" cellspacing="0" >
			<tr>
				<th id="logo" >
					<img src="<?= $this->getSkinUrl ("images/JetRails/TwoFactor/JetRails-Logo.png") ?>" height="150" />
				</th>
				<th id="company" >
					JetRails™<br>Two Factor
				</th>
			</tr>
			<tr id="title" >
				<td colspan="2" >Enter Two Step Verification Code</td>
			</tr>
			<tr>
				<td colspan="2" >
					<form action="<?= $this->_getFormSubmitURL () ?>" method="POST" >
						<input type="hidden" name="form_key" value="<?= $this->getFormKey () ?>" />
						<input type="text" name="pin" value="" placeholder=" 6-Digit Pin " maxlength="6" autocomplete="off" />
						<input type="submit" value="Verify" />
						<br><br><br><br>
						<label for="remember" >Remember for 7 days &nbsp;&nbsp;</label><input type="checkbox" name="remember" id="remember" />
					</form>
				</td>
			</tr>
		</table>
	</body>
</html>