<div class="twofactor-badge" >2FA</div>
<div class="twofactor-container row center" >
	<div class="card col s12" >
		<div class="card-content center">
			<div class="row" >
				<object
					class="twofactor-logo"
					type="image/svg+xml"
					data="<?php echo $this->getSkinUrl ('images/twofactor/logo.svg') ?>" >
					<img src="<?php echo $this->getSkinUrl ('images/twofactor/logo.png') ?>" >
				</object>
			</div>
			<div class="row" >
				<h5 class="col s12 center-align" >You are temporarily blocked!</h5>
			</div>
			<div class="row" >
				<p class="col s12 left-align" >
					<?php echo sprintf (
						$this->__(
							"You failed to enter a valid verification pin and/or backup code. The" .
							" maximum number of failed attempts that is allowed is %s in a span o" .
							"f %s minutes."
						),
						$this->getMaxAttempts (),
						$this->getBlockTime ()
					)?>
				</p>
			</div>
			<div class="row" >
				<p class="col s12 left-align" >
					<?php echo sprintf (
						$this->__(
							"If you are the owner of this account and you are accidentally blocke" .
							"d, it's okay! Just wait %s minutes and you can try to authenticate a" .
							"gain."
						),
						$this->getBlockTime ()
					)?>
				</p>
			</div>
			<div class="row" >
				<p class="col s12 left-align" >
					<?php echo $this->__(
						"Emails have been sent to all administrators regarding this failed attemp" .
						"t to authenticate. An additional email has been sent to the owner of the" .
						" account."
					) ?>
				</p>
			</div>
		</div>
	</div>
</div>