<?php

    /**
     * logout.phtml - 
     * @version         1.0.10
     * @package         JetRails® TwoFactor
     * @category        Template
     * @author          Rafael Grigorian - JetRails®
     * @copyright       JetRails®, all rights reserved
     */

?>
<a
	class="twofactor-logout waves-effect waves-light btn"
	href="<?php echo Mage::helper ('adminhtml')->getUrl ('adminhtml/index/logout') ?>" >
	<?php echo $this->__("Logout") ?>
</a>