<?php

    /**
     * logout.phtml - These page templates are rendered with the help of the block classes that are
     * found under the Template folder for this module.
     * @version         1.1.1
     * @package         JetRails® TwoFactor
     * @category        Template
     * @author          Rafael Grigorian - JetRails®
     * @copyright       JetRails®, all rights reserved
     */

?>
<a
	class="twofactor-logout waves-effect waves-light btn"
	href="<?php echo Mage::helper ('adminhtml')->getUrl ('adminhtml/index/logout') ?>" >
	<?php echo $this->__("Logout") ?>
</a>