<?php

    /**
     * message.phtml - These page templates are rendered with the help of the block classes that are
     * found under the Template folder for this module.
     * @version         1.1.3
     * @package         JetRails® TwoFactor
     * @category        Template
     * @author          Rafael Grigorian - JetRails®
     * @copyright       JetRails®, all rights reserved
     */

?>
<?php foreach ( $this->getMessagesBlock ()->getMessages () as $message ): ?>
	<script>addError ( "<?php echo addslashes ( $message->getText () ) ?>" );</script>
<?php endforeach ?>
