<table class="jetrails_twofactor_description" cellspacing="0" cellpadding="0" >
	<tr>
		<td><div class="jetrails_twofactor_step" >Step 1</div></td>
		<td>Enter in the current time sensitive pin into the text field.</td>
	</tr>
	<tr>
		<td><div class="jetrails_twofactor_step" >Step 2</div></td>
		<td>Click the <u>Disable</u> button to authenticate pin and disable two factor authentication for <u><?= Mage::getSingleton ("admin/session")->getUser ()->getEmail () ?></u></u>.</td>
	</tr>
</table>