<table class="jetrails_twofactor_table" cellspacing="0" >
	<tr style="height:50px;" >
		<td rowspan="4" >
			<img height="180" src="<?= $this->_getQRCode () ?>" />
			<div class="jetrails_twofactor_badge" style="margin-top:-197px;margin-left:-12px;" >1</div>
		</td>
		<td>
			<input class="jetrails_twofactor_pin" type="text" name="code" placeholder="6-digit pin" maxlength="6" autocomplete="off" autofocus />
			<div class="jetrails_twofactor_badge" >2</div>
		</td>
	</tr>
	<tr>
		<td>
			<input class="jetrails_twofactor_submit" type="button" name="<?= $this->_getEnableURL () ?>" value="Enable" onClick="submitTwoFactorPin ()" />
			<div class="jetrails_twofactor_badge" >3</div>
		</td>
	</tr>
</table>